apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myproject-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: nodejs-webapp
      name: nodejs-webapp
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: index.docker.io/myproject/nodejs-webapp:latest
              imagePullPolicy: Always
              name: nodejs-webapp
              ports:
                - containerPort: 8080
              resources: {}
          imagePullSecrets:
            - name: index-docker-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters: []
